# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:MAEjXKp+8hQ/g8CeQFWVzk1pJZK1AuhkINvYGZJrYko=,iv:b95FlHAqxvBbXik6nbIIsAUfyFfKHL+xmdKp7OPrjJU=,tag:+9gHZOpQ3PSUdkJuVpgRUw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1an45nhvv74xhfjfhswzr9sh88yy73ul3hk3xq8prm9dut2dw29jqscq8pz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNElvK2VnRFUxbklMeTdL
        SUZhOVVYV296eGJHMG5IMElxc1Z0ZDg5bXc0CkYxL2hDcXZNUmtsL0F4MzByZ2dw
        NlFSN0htaTNWOEV5NmxGaDJIdXFueFUKLS0tIGJBOFJwbTlPb3prMTlzK1RBSWtl
        cnN4VVZpdHdjVnhZQ0pMWWxFM2krcFUKDOyybnlD2krIQBbLC/qd6G0E5Ma3ya3Q
        sOF/3ZY9tvs3Bevvw1Y+87JHz/lZq+TLlnQujABbrmG05wUJuFStYw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-12T12:33:28Z"
  mac: ENC[AES256_GCM,data:CyGvNAiS96IKj2IFahZ5uMMEN5g6ndN4T05pCXa2OAYlLsok8XphWyCUD+i6uUXtIUiCzBRj3yM5nGVExrMimD26ANl5+S05zDAP9oGFg3nYJxkUdFvPQ5lDKW5VuHYdDF6PkNoTEM/o+24WNMbdKbbAjWm+VHDSCsOSYKmQG3g=,iv:rhpauj+bJpZxoZCVK90pFuiESbiMejc344fxHY5nNXc=,tag:VCKQSO+TNGzg22DvSpNevQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
