apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_EXAMPLE: ENC[AES256_GCM,data:ZcASUQC+mzv6/i/u30njwW5kF0uJvzp2I7ZUhpUBo6SvU9rk9DA98GFOXK3scsUkCMSsIvd+dg6mG0BHC8A0+x85lPR/EFs=,iv:H7DsDq8kZGTonWgA1QqpQqyOnJWg9laQ6FbpjEEPDYs=,tag:VMHnXwk5HtNzhaIwuVBWcg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1an45nhvv74xhfjfhswzr9sh88yy73ul3hk3xq8prm9dut2dw29jqscq8pz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTUU2c3g5dEtIOXdkNXBa
        WkcxK09SMEpSeE1pZFBUWFpuVUhTaDVLeGlBCjVzamdCQ2xQdUNwRFBDVXBueEdj
        dmtHTDVsT2x3djNIdGdFT0dSVStsMzQKLS0tIDRqQkdBTms5RzVRMWVtaFVBSUZo
        N1ZQQ3QwNTRuV1FGZ2Y1dGV2Y09zS1EKhKDxihVl5wtw4DUqgwAlm8T7hMh7u6/o
        1W5ej+MnrgOKuzGqSEe660t/fpsMpnRiCOKbA2R+EdgyAkM2uzfsZQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-12T12:33:28Z"
  mac: ENC[AES256_GCM,data:D8LS3ytZik5+v0wCHmgtW7plKaeyfJs6iJtG3TRYWZOFs9cYaH87lUbim7+WfLGelk93RGoJVTwJIYTphYkg1JCoOFIKv+5ub3YbacUZDehHgb/GOfLn1tOhg/pchYfNfc3MzZSeyGRIIUetdiKaQCjwMTL12yYLybIMiTmYR5g=,iv:nJz4UyGZHPM9fEz33qzQUtPyVtbeIJDgCimyNdU5kSs=,tag:oX/cqPIyDg6Ior6nS18OVw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
